### ISSUE TITLE
small perplexity issues

### ISSUE THREAD

**Issue by speedcell4** [ttpro1995/custom_word_language_model#1]
Hello, I found your post and I am faced with the same problem now. Did you solve that issue? If yes, Could you please give me any hint about what goes wrong? Thx~

https://discuss.pytorch.org/t/word-language-model-result-very-low-perplexity-3-70-with-convolution-layer/4931

**Comment by ttpro1995** [comment]
because the convolution layer accidentally take the "answer" as input, so ... 
yeah, it just see the answer, so perplexity is small.

**Comment by ttpro1995** [comment]
@speedcell4 please try with 1 width convolution filter, so it does not see the answer, which is next character, then see if perplexity be normal. 
If so, then try adding padding, so wider filter does not see the answer either.

**Comment by speedcell4** [comment]
thank you so much, I found my bug
